target1: dep1
	@echo target1 commands: 
	@echo this is the target: $@:$^
	@echo 

dep1: dep2 dep3
	@echo dep1 commands:
	@echo first item aftercolon is: $<
	@echo all items aftercolon are: $^
	@echo 

dep2:
	@echo dep2 commands:
	@echo 

dep3:
